version: "3.6"

services:
  votingapp:
    image: votingapp:${TAG:-latest}
    build:
      context: .
      dockerfile: ./VotingApp.Api/Dockerfile
    environment:
      mongodb: mongodb://db:27017
  
  db:
    image: mongo:4 

  gateway:
    image: gateway:${TAG:-latest}
    build:
      context: ./gateway
    ports:
     - 8080:80
  
  integrationtest:
    image: integrationtest:${TAG:-latest}
    build:
      context: ./integration-test
    environment:
      VOTING_URL: votingapp
      