version: "3.6"

services:
  votingapp:
    image: paulopez/votingapp:2.2
    build:
      context: .
      dockerfile: ./VotingApp.Api/Dockerfile
    ports:
     - 8080:80
  
  integrationtest:
    image: paulopez/integrationtest:2.2
    build:
      context: ./integration-test
    environment:
      VOTING_URL: votingapp
      