apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: votingapp
spec:
  replicas: 3
  selector:
    matchLabels:
      run: votingapp
  template:
    metadata:
      labels:
        run: votingapp
    spec:
      containers:
      - image: votingapp:6
        name: votingapp
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Staging
        - name: Logging__LogLevel__Default
          value: Information
        - name: mongodb
          value: mongodb://database
        livenessProbe: 
          httpGet:
            path: /hc/live
            port: 80
        readinessProbe: 
          httpGet:
            path: /hc/ready
            port: 80
