apiVersion: v1
kind: Service
metadata:
  labels:
    run: votingapp
  name: votingapp
spec:
  ports:
  - nodePort: 32377
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: votingapp
  type: NodePort
